// -----------------------------------------------------------------------
// test_avf_clip_matrix.mm — real-clip format-matrix coverage for the AVF
// (macOS) Decoder-mode Backend. NO Godot, NO RenderingDevice.
//
// Structural mirror of tests/mf/test_mf_clip_matrix.cpp: both platform files
// are thin TEST_CASE wrappers around the shared case bodies in
// tests/common/clip_matrix_cases.h, which drive every clip in
// tests/fixtures/matrix/matrix.list through the platform's Backend and assert
// the same real-world decode contract:
//   - dimensions exact (width/height match the manifest);
//   - decode succeeds with no error;
//   - decoded video frame count within +/-1 of the manifest (GOP/timebase slack);
//   - audio: AAC stereo at 48 kHz, monotonic PTS, ~clip duration of samples;
//   - PTS drift within budget: each video PTS stays within half a frame interval
//     of its ideal index*interval position (real encoder timebase quirks must
//     not accumulate drift).
//   - colorimetry: per-clip matrix/primaries/transfer/range assertions, keyed
//     by clip filename. Untagged clips default to BT.709 video-range. BT.601-
//     tagged clips decode with the SD matrix.
//
// For multi-track clips (audio_tracks > 1 in the manifest) the test also
// verifies track enumeration (count, language tags, default flag) against the
// manifest metadata.
//
// Separate test cases exercise pre-play audio track selection and mid-stream
// track switch (reselect) against the first available multi-track matrix clip,
// providing real-encoder/muxer coverage for both operations.
//
// The manifest and clips are generated by tools/gen_clip_matrix.sh. If the
// script hasn't been run a clip will be missing, and that clip is skipped with
// a WARN — never a hard failure — so the suite stays green in environments
// without the media, exactly like the synthetic-clip test.
// -----------------------------------------------------------------------

#include "vendor/doctest.h"
#include "common/clip_matrix_cases.h"

#include "avf_backend.h"

namespace {

// AVF always has hardware HEVC decode available on the macOS hosts used for
// CI, so the format-matrix case's hevc_available customization point is
// always true here. MF's twin probes for an optional MFT — see
// hevc_decoder_available() in test_mf_clip_matrix.cpp.
constexpr bool kHevcAvailable = true;

// AVF's per-frame CV attachments only carry reliable colorimetry for clips
// with an explicit container tag, and even then only matrix + range (not
// primaries/transfer) — decoder-default attachments on untagged clips vary
// and are not asserted. MF's twin checks all four fields on every frame,
// tagged or not — see check_frame_colorimetry() in test_mf_clip_matrix.cpp.
bool has_explicit_colorimetry(const std::string &file) {
	return file == "h264_30_bt601_mp4.mp4" ||
			file == "hevc_pq_bt2020_30_mp4.mp4" ||
			file == "hevc_hlg_bt2020_30_mp4.mp4";
}

void check_frame_colorimetry(const core::VideoFrame &frame, const std::string &file) {
	if (!has_explicit_colorimetry(file)) {
		return;
	}
	clip_matrix_cases::ColorimetryExpect exp;
	clip_matrix_cases::expect_colorimetry(file, exp);
	CHECK(static_cast<int>(frame.color.matrix) == static_cast<int>(exp.matrix));
	CHECK(static_cast<int>(frame.color.range) == static_cast<int>(exp.range));
}

} // namespace

TEST_CASE("AVF backend decodes the real-clip format matrix") {
	clip_matrix_cases::run_format_matrix_case<avf::AvfBackend>(kHevcAvailable, check_frame_colorimetry);
}

TEST_CASE("AVF backend selects pre-play audio track from multi-track matrix clip") {
	clip_matrix_cases::run_preplay_selection_case<avf::AvfBackend>();
}

TEST_CASE("AVF backend performs mid-stream audio track switch on multi-track matrix clip") {
	clip_matrix_cases::run_midstream_switch_case<avf::AvfBackend>();
}

TEST_CASE("AVF backend reselects to same track on multi-track matrix clip") {
	clip_matrix_cases::run_same_track_reselect_case<avf::AvfBackend>();
}

TEST_CASE("AVF backend reselect clamps out-of-range index on multi-track matrix clip") {
	clip_matrix_cases::run_reselect_clamp_case<avf::AvfBackend>();
}
