// -----------------------------------------------------------------------
// test_avf_clip_matrix.mm — real-clip format-matrix coverage for the AVF
// (macOS) Decoder-mode Backend. NO Godot, NO RenderingDevice.
//
// Drives every clip in tests/fixtures/matrix/matrix.list through
// avf::AvfBackend and asserts the real-world decode contract:
//   - dimensions exact (width/height match the manifest);
//   - decode succeeds with no error;
//   - decoded video frame count within +/-1 of the manifest (GOP/timebase slack);
//   - audio: AAC stereo at 48 kHz, monotonic PTS, ~clip duration of samples;
//   - PTS drift within budget: each video PTS stays within half a frame interval
//     of its ideal index*interval position (real encoder timebase quirks must
//     not accumulate drift).
//   - colorimetry: per-clip matrix/primaries/transfer/range assertions, keyed
//     by clip filename. Untagged clips default to BT.709 video-range (pixel-
//     identical to the old hard-coded constants). BT.601-tagged clips decode
//     with the SD matrix.
//
// The manifest and clips are generated by tools/gen_clip_matrix.sh. If the
// script hasn't been run a clip will be missing, and that clip is skipped with
// a WARN — never a hard failure — so the suite stays green in environments
// without the media, exactly like the synthetic-clip test.
// -----------------------------------------------------------------------

#include "vendor/doctest.h"
#include "common/clip_matrix.h"

#include "avf_backend.h"

#include <cmath>
#include <string>

// -----------------------------------------------------------------------
// Colorimetry expectations per clip filename.
// Untagged clips are not listed here; they must default to BT.709 video range.
// -----------------------------------------------------------------------
struct ColorimetryExpect {
	core::ColorMatrix matrix = core::ColorMatrix::BT709;
	core::ColorPrimaries primaries = core::ColorPrimaries::BT709;
	core::TransferFunction transfer = core::TransferFunction::BT709;
	core::ColorRange range = core::ColorRange::Video;
	int bit_depth = 8;
};

static bool expect_colorimetry(const std::string &file, ColorimetryExpect &out) {
	// BT.601 NTSC-tagged clip. The YCbCr matrix is reliably present in the
	// format description extensions; color primaries and transfer function
	// are often absent (Unspecified) when only the H.264 VUI matrix coefficient
	// is set without the corresponding primaries/transfer VUI fields. The
	// per-frame CV attachments may be more complete.
	if (file == "h264_30_bt601_mp4.mp4") {
		out.matrix = core::ColorMatrix::BT601;
		// Primaries and transfer are not tagged in this clip's format description
		// extensions, so they fall back to the BT.709 defaults.
		out.primaries = core::ColorPrimaries::BT709;
		out.transfer = core::TransferFunction::BT709;
		out.range = core::ColorRange::Video;
		out.bit_depth = 8;
		return true;
	}
	// Untagged — return defaults (which the caller can skip asserting).
	return false;
}

// Assert that the backend's open-time colorimetry matches expectations.
static void check_backend_colorimetry(avf::AvfBackend &backend,
		const std::string &file) {
	ColorimetryExpect exp;
	if (!expect_colorimetry(file, exp)) {
		// Untagged clip: assert defaults (BT.709 video range).
		CHECK(backend.ycbcr_matrix() == core::ColorMatrix::BT709);
		CHECK(backend.color_primaries() == core::ColorPrimaries::BT709);
		CHECK(backend.transfer_function() == core::TransferFunction::BT709);
		CHECK(backend.color_range() == core::ColorRange::Video);
		CHECK(backend.bit_depth() == 8);
		return;
	}
	CHECK(backend.ycbcr_matrix() == exp.matrix);
	CHECK(backend.color_primaries() == exp.primaries);
	CHECK(backend.transfer_function() == exp.transfer);
	CHECK(backend.color_range() == exp.range);
	CHECK(backend.bit_depth() == exp.bit_depth);
}

// Assert that the per-frame colorimetry matches expectations.
// The first decoded frame's metadata should match the open-time negotiated values.
static void check_frame_colorimetry(const core::VideoFrame &frame,
		const std::string &file) {
	ColorimetryExpect exp;
	if (!expect_colorimetry(file, exp)) {
		// Untagged frame: default fields are Unspecified (CV attachments absent),
		// which the shader handles as BT.709/video-range — same as today.
		// We just verify they exist and are valid.
		return;
	}
	// Tagged clip: CV attachments carry the exact metadata.
	CHECK(static_cast<int>(frame.ycbcr_matrix) == static_cast<int>(exp.matrix));
	CHECK(static_cast<int>(frame.range) == static_cast<int>(exp.range));
}

TEST_CASE("AVF backend decodes the real-clip format matrix") {
	const auto clips = clip_matrix::load();
	if (clips.empty()) {
		WARN_MESSAGE(false, "clip matrix manifest absent — skipping real-clip coverage");
		return;
	}

	int decoded_clips = 0;

	for (const auto &clip : clips) {
		const std::string path = clip_matrix::clip_path(clip);

		if (!clip_matrix::file_exists(path)) {
			WARN_MESSAGE(false, ("matrix clip missing (run tools/gen_clip_matrix.sh): " + clip.file).c_str());
			continue;
		}

		CAPTURE(clip.file);

		avf::AvfBackend backend;
		REQUIRE(backend.open(path));

		// --- Dimensions: exact ---
		CHECK(backend.video_width() == clip.width);
		CHECK(backend.video_height() == clip.height);

		// --- Colorimetry: open-time values ---
		check_backend_colorimetry(backend, clip.file);

		// --- Audio track shape: AAC stereo @ 48 kHz ---
		CHECK(backend.audio_sample_rate() == clip.audio_rate);
		CHECK(backend.audio_channel_count() == clip.audio_channels);

		// --- Video: decode-success + count + PTS drift within budget ---
		const double interval = 1.0 / static_cast<double>(clip.fps);
		const double budget = interval * 0.5; // half a frame interval

		int video_count = 0;
		double last_pts = -1.0;
		double max_drift = 0.0;
		bool first_frame = true;
		while (auto frame = backend.next_video_frame()) {
			CHECK(frame->pixel_format == core::PixelFormat::NV12);
			CHECK(frame->native_handle != nullptr);
			CHECK(frame->width == clip.width);
			CHECK(frame->height == clip.height);

			// Colorimetry per frame: check the first frame's attachments.
			if (first_frame) {
				check_frame_colorimetry(*frame, clip.file);
				first_frame = false;
			}

			// Monotonic non-decreasing PTS.
			CHECK(frame->pts_seconds >= last_pts);
			last_pts = frame->pts_seconds;

			// Drift of this frame's PTS from its ideal index*interval slot.
			const double ideal = static_cast<double>(video_count) * interval;
			const double drift = std::fabs(frame->pts_seconds - ideal);
			if (drift > max_drift) {
				max_drift = drift;
			}

			frame->release();
			++video_count;
		}

		CHECK_FALSE(backend.had_error());
		CHECK(video_count >= clip.frames - 1);
		CHECK(video_count <= clip.frames + 1);
		CHECK(max_drift <= budget);

		// --- Audio: re-open (single-pass reader), pump PCM, monotonic PTS ---
		REQUIRE(backend.open(path));
		long audio_frames_total = 0;
		double last_audio_pts = -1.0;
		int audio_chunks = 0;
		while (auto chunk = backend.next_audio_chunk()) {
			CHECK(chunk->samples != nullptr);
			CHECK(chunk->frame_count > 0);
			CHECK(chunk->channel_count == clip.audio_channels);
			CHECK(chunk->sample_rate == clip.audio_rate);
			CHECK(chunk->pts_seconds >= last_audio_pts);
			last_audio_pts = chunk->pts_seconds;
			audio_frames_total += chunk->frame_count;
			++audio_chunks;
		}
		CHECK_FALSE(backend.had_error());
		CHECK(audio_chunks > 0);

		// At least half the nominal duration of samples (AAC priming/padding fuzz).
		const long nominal =
				static_cast<long>(static_cast<double>(clip.audio_rate) * clip.frames / clip.fps);
		CHECK(audio_frames_total >= nominal / 2);

		++decoded_clips;
	}

	// If the manifest listed clips but none were decodable (all missing), warn
	// loudly so an operator knows coverage didn't actually run.
	if (decoded_clips == 0) {
		WARN_MESSAGE(false, "no matrix clips were decodable — run tools/gen_clip_matrix.sh");
	}
}
