// -----------------------------------------------------------------------
// test_avf_clip_matrix.mm — real-clip format-matrix coverage for the AVF
// (macOS) Decoder-mode Backend. NO Godot, NO RenderingDevice.
//
// Drives every clip in tests/fixtures/matrix/matrix.list through
// avf::AvfBackend and asserts the real-world decode contract:
//   - dimensions exact (width/height match the manifest);
//   - decode succeeds with no error;
//   - decoded video frame count within +/-1 of the manifest (GOP/timebase slack);
//   - audio: AAC stereo at 48 kHz, monotonic PTS, ~clip duration of samples;
//   - PTS drift within budget: each video PTS stays within half a frame interval
//     of its ideal index*interval position (real encoder timebase quirks must
//     not accumulate drift).
//   - colorimetry: per-clip matrix/primaries/transfer/range assertions, keyed
//     by clip filename. Untagged clips default to BT.709 video-range (pixel-
//     identical to the old hard-coded constants). BT.601-tagged clips decode
//     with the SD matrix.
//
// The manifest and clips are generated by tools/gen_clip_matrix.sh. If the
// script hasn't been run a clip will be missing, and that clip is skipped with
// a WARN — never a hard failure — so the suite stays green in environments
// without the media, exactly like the synthetic-clip test.
// -----------------------------------------------------------------------

#include "vendor/doctest.h"
#include "common/clip_matrix.h"

#include "avf_backend.h"

#include <cmath>
#include <string>

// -----------------------------------------------------------------------
// Colorimetry expectations per clip filename.
// Untagged clips are not listed here; they must default to BT.709 video range.
// -----------------------------------------------------------------------
struct ColorimetryExpect {
	core::ColorMatrix matrix = core::ColorMatrix::BT709;
	core::ColorPrimaries primaries = core::ColorPrimaries::BT709;
	core::TransferFunction transfer = core::TransferFunction::BT709;
	core::ColorRange range = core::ColorRange::Video;
	int bit_depth = 8;
};

static bool expect_colorimetry(const std::string &file, ColorimetryExpect &out) {
	// BT.601 NTSC-tagged clip. The generator forces the ISOBMFF 'colr' box
	// (-movflags +write_colr), so the format description extensions carry the
	// full SD tags: BT.601 matrix and SMPTE-C primaries. The SMPTE 170M
	// transfer function is curve-identical to BT.709 and CoreMedia
	// canonicalizes it as such.
	if (file == "h264_30_bt601_mp4.mp4") {
		out.matrix = core::ColorMatrix::BT601;
		out.primaries = core::ColorPrimaries::BT601_525;
		out.transfer = core::TransferFunction::BT709;
		out.range = core::ColorRange::Video;
		out.bit_depth = 8;
		return true;
	}
	// HEVC Main10 SDR clip. Negotiates as 10-bit biplanar (x420). The bit
	// depth is detected from the format description's BitsPerComponent (10).
	// The format description extensions have no colorimetry tags (ffmpeg
	// default), so open-time defaults to BT.709 video range. Per-frame CV
	// attachments carry BT.601 matrix (ffmpeg color filter default).
	if (file == "hevc_main10_30_mp4.mp4") {
		out.matrix = core::ColorMatrix::BT709;
		out.primaries = core::ColorPrimaries::BT709;
		out.transfer = core::TransferFunction::BT709;
		out.range = core::ColorRange::Video;
		out.bit_depth = 10;
		return true;
	}
	// HDR10 clip: PQ transfer, BT.2020 primaries, BT.2020 non-constant
	// luminance matrix. 10-bit.
	if (file == "hevc_pq_bt2020_30_mp4.mp4") {
		out.matrix = core::ColorMatrix::BT2020;
		out.primaries = core::ColorPrimaries::BT2020;
		out.transfer = core::TransferFunction::PQ;
		out.range = core::ColorRange::Video;
		out.bit_depth = 10;
		return true;
	}
	// HLG clip: HLG transfer, BT.2020 primaries, BT.2020 non-constant
	// luminance matrix. 10-bit.
	if (file == "hevc_hlg_bt2020_30_mp4.mp4") {
		out.matrix = core::ColorMatrix::BT2020;
		out.primaries = core::ColorPrimaries::BT2020;
		out.transfer = core::TransferFunction::HLG;
		out.range = core::ColorRange::Video;
		out.bit_depth = 10;
		return true;
	}

	// Untagged — return defaults (which the caller can skip asserting).
	return false;
}

// Assert that the backend's open-time colorimetry matches expectations.
static void check_backend_colorimetry(avf::AvfBackend &backend,
		const std::string &file) {
	const core::Colorimetry color = backend.colorimetry();
	ColorimetryExpect exp;
	if (!expect_colorimetry(file, exp)) {
		// Untagged clip: assert defaults (BT.709 video range).
		CHECK(color.matrix == core::ColorMatrix::BT709);
		CHECK(color.primaries == core::ColorPrimaries::BT709);
		CHECK(color.transfer == core::TransferFunction::BT709);
		CHECK(color.range == core::ColorRange::Video);
		CHECK(color.bit_depth == 8);
		return;
	}
	CHECK(color.matrix == exp.matrix);
	CHECK(color.primaries == exp.primaries);
	CHECK(color.transfer == exp.transfer);
	CHECK(color.range == exp.range);
	CHECK(color.bit_depth == exp.bit_depth);
}

// True for clips whose format description carries explicit colorimetry tags
// (matrix, primaries, transfer function). Untagged clips (including ffmpeg
// defaults) return false; the per-frame CV attachments may carry arbitrary
// decoder defaults that differ from the open-time negotiated values.
static bool has_explicit_colorimetry(const std::string &file) {
	return file == "h264_30_bt601_mp4.mp4" ||
		file == "hevc_pq_bt2020_30_mp4.mp4" ||
		file == "hevc_hlg_bt2020_30_mp4.mp4";
}

// Assert that the per-frame colorimetry matches expectations.
// Only meaningful for clips with explicit colorimetry tags in the format
// description; untagged clips have decoder-default CV attachments that vary.
static void check_frame_colorimetry(const core::VideoFrame &frame,
		const std::string &file) {
	if (!has_explicit_colorimetry(file)) {
		// Untagged frame: default fields are Unspecified or decoder-defaults,
		// which the shader handles as BT.709/video-range — same as today.
		return;
	}
	ColorimetryExpect exp;
	expect_colorimetry(file, exp);
	// Tagged clip: CV attachments carry the exact metadata.
	CHECK(static_cast<int>(frame.color.matrix) == static_cast<int>(exp.matrix));
	CHECK(static_cast<int>(frame.color.range) == static_cast<int>(exp.range));
}

TEST_CASE("AVF backend decodes the real-clip format matrix") {
	const auto clips = clip_matrix::load();
	if (clips.empty()) {
		WARN_MESSAGE(false, "clip matrix manifest absent — skipping real-clip coverage");
		return;
	}

	int decoded_clips = 0;

	for (const auto &clip : clips) {
		const std::string path = clip_matrix::clip_path(clip);

		if (!clip_matrix::file_exists(path)) {
			WARN_MESSAGE(false, ("matrix clip missing (run tools/gen_clip_matrix.sh): " + clip.file).c_str());
			continue;
		}

		CAPTURE(clip.file);

		avf::AvfBackend backend;
		REQUIRE(backend.open(path));

		// --- Dimensions: exact ---
		CHECK(backend.video_width() == clip.width);
		CHECK(backend.video_height() == clip.height);

		// --- Colorimetry: open-time values ---
		check_backend_colorimetry(backend, clip.file);

		// --- Audio track shape: AAC stereo @ 48 kHz ---
		CHECK(backend.audio_sample_rate() == clip.audio_rate);
		CHECK(backend.audio_channel_count() == clip.audio_channels);

		// --- Video: decode-success + count + PTS drift within budget ---
		const double interval = 1.0 / static_cast<double>(clip.fps);
		const double budget = interval * 0.5; // half a frame interval

		int video_count = 0;
		double last_pts = -1.0;
		double max_drift = 0.0;
		bool first_frame = true;
		while (auto frame = backend.next_video_frame()) {
			// 8-bit sources produce NV12; 10-bit sources produce x420.
			ColorimetryExpect exp;
			const bool is_10bit = expect_colorimetry(clip.file, exp) && exp.bit_depth >= 10;
			if (is_10bit) {
				CHECK(frame->pixel_format == core::PixelFormat::x420);
				CHECK(frame->color.bit_depth == 10);
			} else {
				CHECK(frame->pixel_format == core::PixelFormat::NV12);
				CHECK(frame->color.bit_depth == 8);
			}
			CHECK(frame->native_handle != nullptr);
			CHECK(frame->width == clip.width);
			CHECK(frame->height == clip.height);

			// Colorimetry per frame: check the first frame's attachments.
			if (first_frame) {
				check_frame_colorimetry(*frame, clip.file);
				first_frame = false;
			}

			// Monotonic non-decreasing PTS.
			CHECK(frame->pts_seconds >= last_pts);
			last_pts = frame->pts_seconds;

			// Drift of this frame's PTS from its ideal index*interval slot.
			const double ideal = static_cast<double>(video_count) * interval;
			const double drift = std::fabs(frame->pts_seconds - ideal);
			if (drift > max_drift) {
				max_drift = drift;
			}

			frame->release();
			++video_count;
		}

		CHECK_FALSE(backend.had_error());
		CHECK(video_count >= clip.frames - 1);
		CHECK(video_count <= clip.frames + 1);
		CHECK(max_drift <= budget);

		// --- Audio: re-open (single-pass reader), pump PCM, monotonic PTS ---
		REQUIRE(backend.open(path));
		long audio_frames_total = 0;
		double last_audio_pts = -1.0;
		int audio_chunks = 0;
		while (auto chunk = backend.next_audio_chunk()) {
			CHECK(chunk->samples != nullptr);
			CHECK(chunk->frame_count > 0);
			CHECK(chunk->channel_count == clip.audio_channels);
			CHECK(chunk->sample_rate == clip.audio_rate);
			CHECK(chunk->pts_seconds >= last_audio_pts);
			last_audio_pts = chunk->pts_seconds;
			audio_frames_total += chunk->frame_count;
			++audio_chunks;
		}
		CHECK_FALSE(backend.had_error());
		CHECK(audio_chunks > 0);

		// At least half the nominal duration of samples (AAC priming/padding fuzz).
		const long nominal =
				static_cast<long>(static_cast<double>(clip.audio_rate) * clip.frames / clip.fps);
		CHECK(audio_frames_total >= nominal / 2);

		++decoded_clips;
	}

	// If the manifest listed clips but none were decodable (all missing), warn
	// loudly so an operator knows coverage didn't actually run.
	if (decoded_clips == 0) {
		WARN_MESSAGE(false, "no matrix clips were decodable — run tools/gen_clip_matrix.sh");
	}
}
