#pragma once
// -----------------------------------------------------------------------
// clip_matrix.h — tiny, dependency-free reader for the real-clip format
// matrix manifest (tests/fixtures/matrix/matrix.list).
//
// Shared by the per-platform backend coverage tests (AVF on macOS, MF on
// Windows). It parses the whitespace-separated plain-text manifest — NOT the
// JSON — so the headless test binaries pull in no JSON dependency.
//
// Basic columns (always present):
//   file  width  height  fps  frames  audio_channels  audio_rate
//
// Multi-track columns (present only for clips with >1 audio track):
//   audio_tracks  default_track  lang1  lang2 ...
//
// Single-track clips are stored with the basic 7 columns only (backwards
// compatible). The parser defaults audio_tracks=1, default_track=0, and an
// empty language vector when only 7 columns are found.
//
// The manifest and the clips are generated by tools/gen_clip_matrix.sh and are
// not committed. If the script hasn't been run, the manifest (or a per-clip
// file) simply won't exist; the coverage test treats that as "skip with WARN",
// never a failure, mirroring how the synthetic-clip tests degrade when ffmpeg
// is absent.
// -----------------------------------------------------------------------

#include <cstdlib>
#include <fstream>
#include <sstream>
#include <string>
#include <sys/stat.h>
#include <vector>

namespace clip_matrix {

struct Clip {
	std::string file; // basename, e.g. "h264_30_mp4.mp4"
	int width = 0;
	int height = 0;
	int fps = 0;
	int frames = 0;
	int audio_channels = 0; // per-track channel count
	int audio_rate = 0;
	int audio_tracks = 1;   // number of audio tracks (1 for single-track clips)
	int default_track = 0;  // index of the default audio track
	std::vector<std::string> track_languages; // BCP 47 tags per track; empty for single-track
};

inline bool file_exists(const std::string &p) {
	struct stat st;
	return ::stat(p.c_str(), &st) == 0;
}

// Repo root: REPO_ROOT env override, else "." (scons runs tests from root).
inline std::string repo_root() {
	if (const char *env = std::getenv("REPO_ROOT")) {
		return std::string(env);
	}
	return ".";
}

inline std::string matrix_dir() {
	return repo_root() + "/tests/fixtures/matrix";
}

// Parse matrix.list. Returns empty if the manifest is absent or unreadable.
inline std::vector<Clip> load() {
	std::vector<Clip> clips;
	const std::string manifest = matrix_dir() + "/matrix.list";
	std::ifstream in(manifest);
	if (!in) {
		return clips;
	}
	std::string line;
	while (std::getline(in, line)) {
		// Strip a trailing CR (manifest may arrive with CRLF on Windows).
		if (!line.empty() && line.back() == '\r') {
			line.pop_back();
		}
		// Skip blanks and comments.
		std::size_t first = line.find_first_not_of(" \t");
		if (first == std::string::npos || line[first] == '#') {
			continue;
		}
			std::istringstream ss(line);
		Clip c;
		if (ss >> c.file >> c.width >> c.height >> c.fps >> c.frames >> c.audio_channels >> c.audio_rate) {
			// Try to parse multi-track columns (audio_tracks, default_track, languages).
			// If absent the stream will fail, leaving defaults unchanged.
			int at;
			if (ss >> at) {
				c.audio_tracks = at;
				int dt;
				if (ss >> dt) {
					c.default_track = dt;
					std::string lang;
					while (ss >> lang) {
						c.track_languages.push_back(lang);
					}
				}
			}
			clips.push_back(c);
		}
	}
	return clips;
}

// Absolute path to a clip's binary file.
inline std::string clip_path(const Clip &c) {
	return matrix_dir() + "/" + c.file;
}

// First clip in the manifest with at least `min_tracks` audio tracks, or
// nullptr if none qualifies. Shared by the AVF/MF multi-track matrix cases,
// which all drive their pre-play-selection / reselect coverage off the first
// available multi-track real clip.
inline const Clip *find_multi_track_clip(const std::vector<Clip> &clips, int min_tracks = 2) {
	for (const auto &clip : clips) {
		if (clip.audio_tracks >= min_tracks) {
			return &clip;
		}
	}
	return nullptr;
}

} // namespace clip_matrix
