#!/usr/bin/env bash
# tools/gen_stress_media.sh
# -----------------------------------------------------------------------
# Real-world-quirk stress-media generator — test tooling only; never a
# runtime dep.
#
# Our synthetic marker clip (tools/gen_test_media.sh) and the clip matrix
# (tools/gen_clip_matrix.sh) are all-intra or B-frame-free with mono/stereo
# audio, so neither one exercises frame-reordering (B-frames) or multi-
# channel audio decode paths. A real-world H.264/5.1/.mov file exposed bugs
# in both that the synthetic corpus was blind to. This script produces small,
# targeted clips that isolate each quirk so regressions get caught by
# regenerable synthetic media instead of a single hand-collected real file:
#
#   bframes.mp4        H.264 High profile WITH B-frames (frame reordering)
#   surround51.mp4      6-channel 5.1 AAC, 48 kHz, one distinct tone per
#                        channel (audibly catches channel-order bugs)
#   timecode.mov         .mov with a tmcd timecode track ahead of the audio
#                        stream (video=0, tmcd=1, audio=2 — matches the
#                        real-world file's layout) + B-frames + stereo audio
#   combined_stress.mov  everything at once: B-frames + 5.1 audio + tmcd
#                        track in a .mov container
#   marker_bframes.mp4   H.264 WITH B-frames, 24 fps, ~10s, stereo AAC, and
#                        (unlike every other clip above) every frame's
#                        content numerically encodes its own frame index —
#                        a "frame identity probe" fixture. PTS/stream-
#                        position telemetry can't see a decoder or present-
#                        path bug that shows the wrong *decoded frame*
#                        while reporting a perfectly monotonic position; this
#                        clip lets a readback probe decode which frame is
#                        actually on screen and catch backward/repeated/
#                        skipped presented frames directly. See the
#                        gen_marker_bframes()/decode_marker_value() comments
#                        below for the block encoding.
#
# heaac.mp4 (HE-AAC/SBR) is intentionally NOT generated by this script: this
# ffmpeg build has no libfdk_aac encoder, and while the native `aac` encoder
# accepts `-profile:a aac_he` without erroring, ffmpeg's own native `aac`
# decoder then fails to read the file back ("Audio object type SBR+21 is not
# implemented"), so the output could not even be verified with ffprobe, let
# alone trusted as real SBR bitstream. Faking it would defeat the point of a
# stress clip. Skipped; see AGENTS/README notes for the limitation.
#
# Usage:
#   tools/gen_stress_media.sh [--output-dir DIR] [--duration SECONDS]
#
# Defaults:
#   --output-dir  tests/fixtures/stress
#   --duration    6   (seconds per clip; keep clips short)
#
# Requirements:
#   ffmpeg >= 4.0 with libx264 in PATH (test-only; never shipped).
# -----------------------------------------------------------------------
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

OUTPUT_DIR="${REPO_ROOT}/tests/fixtures/stress"
DURATION=6

while [[ $# -gt 0 ]]; do
    case "$1" in
        --output-dir) OUTPUT_DIR="$2"; shift 2 ;;
        --duration)   DURATION="$2";   shift 2 ;;
        *) echo "Unknown argument: $1" >&2; exit 1 ;;
    esac
done

command -v ffmpeg >/dev/null 2>&1 || {
    echo "ERROR: ffmpeg not found in PATH. Install ffmpeg to generate stress media." >&2
    exit 1
}

mkdir -p "${OUTPUT_DIR}"

# drawtext font selection. On Windows, fontconfig-enabled ffmpeg builds crash
# resolving a font *family* (no fontconfig config file ships with the binary),
# so point freetype at a concrete font file instead. Elsewhere the family
# lookup works and stays font-installation agnostic. (Same trick as
# tools/gen_test_media.sh and tools/gen_clip_matrix.sh.)
if [[ "${OS:-}" == "Windows_NT" ]]; then
    DRAWTEXT_FONT="fontfile='C\\:/Windows/Fonts/consola.ttf'"
else
    DRAWTEXT_FONT="font=monospace"
fi

# drawtext requires ffmpeg built --enable-libfreetype; stripped/minimal
# ffmpeg builds (common on some CI images) omit it. Detect once up front and
# degrade to a labelless (but otherwise identical) filtergraph instead of
# aborting -- the label is purely cosmetic, never load-bearing for any
# self-check below.
if ffmpeg -hide_banner -filters 2>/dev/null | grep -qw drawtext; then
    HAVE_DRAWTEXT=1
else
    HAVE_DRAWTEXT=0
    echo "WARN: drawtext filter unavailable (ffmpeg built without --enable-libfreetype);" >&2
    echo "      generating clips without burned-in labels." >&2
fi

WIDTH=320
HEIGHT=240
SAMPLE_RATE=48000

# libx264 flags shared by every clip that needs real (non-adaptive) B-frames:
# 3 consecutive B-frames, adaptive B-frame placement disabled so the encoder
# always inserts them deterministically rather than skipping them when the
# heuristic decides they're not worth it on low-motion synthetic content.
BFRAME_ARGS=(-bf 3 -x264opts "bframes=3:b-adapt=0")

# Moving test pattern + a burned-in label so the clips are easy to eyeball
# and tell apart once copied next to real fixtures. testsrc2 has continuous
# motion (unlike a static color field), which is what actually gives x264
# something to B-predict against.
#
# Split in two: video_src emits the plain -f lavfi -i source (lavfi inputs
# don't support named output pads directly), video_label_filter is a
# -filter_complex fragment applied to that input's [N:v] to burn in the
# label — kept separate so callers can pick the input index.
video_src() {
    local fps="$1"
    echo "testsrc2=size=${WIDTH}x${HEIGHT}:rate=${fps}:duration=${DURATION}"
}

video_label_filter() {
    local in_idx="$1" label="$2"
    if [[ "${HAVE_DRAWTEXT}" -eq 1 ]]; then
        echo "[${in_idx}:v]drawtext=text='${label} %{eif\:n\:d}':x=10:y=10:fontsize=24:fontcolor=white:box=1:boxcolor=black@0.5:${DRAWTEXT_FONT}[video_out]"
    else
        echo "[${in_idx}:v]null[video_out]"
    fi
}

# -----------------------------------------------------------------------
# bframes.mp4 — H.264 High profile, real B-frames, 24 fps, stereo AAC.
# -----------------------------------------------------------------------
gen_bframes() {
    local out="${OUTPUT_DIR}/bframes.mp4"
    echo "Generating bframes.mp4: H.264 High profile, bf=3 b-adapt=0, 24fps, stereo AAC -> ${out}"
    ffmpeg -y -hide_banner -loglevel error \
        -f lavfi -i "$(video_src 24)" \
        -f lavfi -i "sine=frequency=300:duration=${DURATION}" \
        -f lavfi -i "sine=frequency=500:duration=${DURATION}" \
        -filter_complex "$(video_label_filter 0 BFRAMES);[1:a][2:a]amerge=inputs=2[aout]" \
        -map "[video_out]" -map "[aout]" \
        -c:v libx264 -profile:v high -preset fast -crf 20 -pix_fmt yuv420p -g 48 "${BFRAME_ARGS[@]}" \
        -c:a aac -b:a 128k -ar "${SAMPLE_RATE}" -ac 2 \
        -movflags +faststart \
        "${out}" </dev/null
}

# -----------------------------------------------------------------------
# surround51.mp4 — no B-frames, 6-channel 5.1 AAC 48 kHz. Each channel gets
# its own tone (FL=220 FR=440 FC=880 LFE=55 BL=1760 BR=3520 Hz) so a
# misrouted channel is audible, not just a channel-count assertion.
# -----------------------------------------------------------------------
gen_surround51() {
    local out="${OUTPUT_DIR}/surround51.mp4"
    echo "Generating surround51.mp4: no B-frames, 5.1 AAC 48kHz (per-channel tones) -> ${out}"
    ffmpeg -y -hide_banner -loglevel error \
        -f lavfi -i "$(video_src 30)" \
        -filter_complex "$(video_label_filter 0 SURROUND51);sine=f=220:d=${DURATION}[c0];sine=f=440:d=${DURATION}[c1];sine=f=880:d=${DURATION}[c2];sine=f=55:d=${DURATION}[c3];sine=f=1760:d=${DURATION}[c4];sine=f=3520:d=${DURATION}[c5];[c0][c1][c2][c3][c4][c5]amerge=inputs=6[am];[am]pan=5.1|FL=c0|FR=c1|FC=c2|LFE=c3|BL=c4|BR=c5[aout]" \
        -map "[video_out]" -map "[aout]" \
        -c:v libx264 -preset fast -crf 20 -pix_fmt yuv420p -bf 0 \
        -c:a aac -b:a 384k -ar "${SAMPLE_RATE}" \
        -movflags +faststart \
        "${out}" </dev/null
}

# -----------------------------------------------------------------------
# timecode.mov — .mov with a tmcd track ahead of the audio stream, matching
# the real-world file's layout (video=0, tmcd=1, audio=2), plus B-frames and
# stereo audio.
#
# The mov muxer always appends an auto-generated tmcd track after every
# explicitly mapped stream in a single-pass invocation, which gives
# video=0, audio=1, tmcd=2 — the wrong order. To land tmcd at index 1 we
# encode video+timecode first (nothing else to append after), then remux
# that alongside separately-encoded audio with explicit -map order.
# -----------------------------------------------------------------------
gen_timecode() {
    local out="${OUTPUT_DIR}/timecode.mov"
    local video_tmp="${OUTPUT_DIR}/.timecode_video_tmp.mov"
    echo "Generating timecode.mov: mov + tmcd track + B-frames + stereo AAC -> ${out}"

    ffmpeg -y -hide_banner -loglevel error \
        -f lavfi -i "$(video_src 24)" \
        -filter_complex "$(video_label_filter 0 TIMECODE)" \
        -map "[video_out]" \
        -c:v libx264 -profile:v high -preset fast -crf 20 -pix_fmt yuv420p -g 48 "${BFRAME_ARGS[@]}" \
        -timecode 00:00:00:00 \
        -f mov "${video_tmp}" </dev/null

    ffmpeg -y -hide_banner -loglevel error \
        -i "${video_tmp}" \
        -f lavfi -i "sine=frequency=300:duration=${DURATION}" \
        -f lavfi -i "sine=frequency=500:duration=${DURATION}" \
        -filter_complex "[1:a][2:a]amerge=inputs=2[aout]" \
        -map 0:v -map 0:d -map "[aout]" \
        -c:v copy -c:d copy \
        -c:a aac -b:a 128k -ar "${SAMPLE_RATE}" -ac 2 \
        -movflags +faststart \
        -f mov "${out}" </dev/null

    rm -f "${video_tmp}"
}

# -----------------------------------------------------------------------
# combined_stress.mov — the "everything at once" case: B-frames + 5.1 48kHz
# audio + tmcd track in a .mov container. Same two-pass trick as
# gen_timecode to get the video/tmcd/audio stream order right.
# -----------------------------------------------------------------------
gen_combined() {
    local out="${OUTPUT_DIR}/combined_stress.mov"
    local video_tmp="${OUTPUT_DIR}/.combined_video_tmp.mov"
    echo "Generating combined_stress.mov: B-frames + 5.1 AAC 48kHz + tmcd in .mov -> ${out}"

    ffmpeg -y -hide_banner -loglevel error \
        -f lavfi -i "$(video_src 24)" \
        -filter_complex "$(video_label_filter 0 COMBINED)" \
        -map "[video_out]" \
        -c:v libx264 -profile:v high -preset fast -crf 20 -pix_fmt yuv420p -g 48 "${BFRAME_ARGS[@]}" \
        -timecode 00:00:00:00 \
        -f mov "${video_tmp}" </dev/null

    ffmpeg -y -hide_banner -loglevel error \
        -i "${video_tmp}" \
        -filter_complex "sine=f=220:d=${DURATION}[c0];sine=f=440:d=${DURATION}[c1];sine=f=880:d=${DURATION}[c2];sine=f=55:d=${DURATION}[c3];sine=f=1760:d=${DURATION}[c4];sine=f=3520:d=${DURATION}[c5];[c0][c1][c2][c3][c4][c5]amerge=inputs=6[am];[am]pan=5.1|FL=c0|FR=c1|FC=c2|LFE=c3|BL=c4|BR=c5[aout]" \
        -map 0:v -map 0:d -map "[aout]" \
        -c:v copy -c:d copy \
        -c:a aac -b:a 384k -ar "${SAMPLE_RATE}" \
        -movflags +faststart \
        -f mov "${out}" </dev/null

    rm -f "${video_tmp}"
}

# -----------------------------------------------------------------------
# marker_bframes.mp4 — H.264 High profile with real B-frames (same
# BFRAME_ARGS as bframes.mp4 above), 24 fps, ~10s, stereo AAC, where every
# frame's *content* encodes its own frame index as a binary number.
#
# Encoding: the frame is divided into MARKER_BITS equal-width full-height
# vertical blocks laid out left-to-right (a "horizontal strip" of blocks),
# MSB first. Block i is solid white (luma 255) if bit (MARKER_BITS-1-i) of
# the frame number is set, else solid black (luma 0); chroma is pinned to
# neutral gray (128/128) so the marker rides on luma only and is immune to
# 4:2:0 chroma subsampling. MARKER_BITS=10 (block width 320/10=32px, a
# multiple of the 16px macroblock size, so block edges land on macroblock
# boundaries instead of splitting one) comfortably covers frame indices
# 0-1023 -- far more than the ~240 frames in this clip -- and each 32px-wide
# block survives CRF 15 x264 compression as a clean, unambiguous bit: a
# reader can sample a single pixel at each block's center row/column and
# threshold at luma 128.
#
# The whole thing is one geq filter: lum picks 255 or 0 per pixel from
# bitand(N, 2^bit) where N is ffmpeg's frame-number variable and the bit
# index comes from the pixel's X coordinate. This was verified end-to-end
# (raw geq output, then again after full H.264 encode+decode) by
# decode_marker_value() below/in the verification step this script runs
# after generating the clip -- see run_marker_bframes_selfcheck.
# -----------------------------------------------------------------------
MARKER_BITS=10
MARKER_FPS=24
MARKER_DURATION=10

gen_marker_bframes() {
    local out="${OUTPUT_DIR}/marker_bframes.mp4"
    local frames=$(( MARKER_FPS * MARKER_DURATION ))
    local blockw=$(( WIDTH / MARKER_BITS ))
    local lum_expr="255*eq(bitand(N\,pow(2\,${MARKER_BITS}-1-floor(X/${blockw}))),pow(2\,${MARKER_BITS}-1-floor(X/${blockw})))"

    echo "Generating marker_bframes.mp4: H.264 High profile, bf=3 b-adapt=0, ${MARKER_FPS}fps, ${frames} frames, ${MARKER_BITS}-bit frame-index marker, stereo AAC -> ${out}"

    ffmpeg -y -hide_banner -loglevel error \
        -f lavfi -i "color=black:size=${WIDTH}x${HEIGHT}:rate=${MARKER_FPS}:duration=${MARKER_DURATION}" \
        -f lavfi -i "sine=frequency=300:duration=${MARKER_DURATION}" \
        -f lavfi -i "sine=frequency=500:duration=${MARKER_DURATION}" \
        -filter_complex "[0:v]geq=lum='${lum_expr}':cb=128:cr=128[video_out];[1:a][2:a]amerge=inputs=2[aout]" \
        -map "[video_out]" -map "[aout]" \
        -c:v libx264 -profile:v high -preset fast -crf 15 -pix_fmt yuv420p -g 48 "${BFRAME_ARGS[@]}" \
        -c:a aac -b:a 128k -ar "${SAMPLE_RATE}" -ac 2 \
        -frames:v "${frames}" \
        -movflags +faststart \
        "${out}" </dev/null
}

# -----------------------------------------------------------------------
# decode_marker_value — read back frame $2 of marker clip $1 and decode its
# MARKER_BITS-bit frame-index marker to a plain integer. Samples one pixel
# per block (block-center column, mid-height row) from a raw-gray decode of
# just that frame; no image library needed, just ffmpeg + dd + od (all
# already required by this repo's other test tooling). Used by
# run_marker_bframes_selfcheck below, and reusable by anything else (e.g. a
# CI check) that wants to sanity-check the marker without a GDScript engine.
# -----------------------------------------------------------------------
decode_marker_value() {
    local file="$1" n="$2" width="$3" height="$4" bits="$5"
    local tmp
    tmp="$(mktemp)"
    ffmpeg -y -hide_banner -loglevel error -i "${file}" \
        -vf "select=eq(n\,${n}),format=gray" -vsync 0 -f rawvideo -frames:v 1 "${tmp}" </dev/null

    local blockw=$(( width / bits ))
    local yoff=$(( (height / 2) * width ))
    local val=0 i xoff byte bit
    for ((i = 0; i < bits; i++)); do
        xoff=$(( yoff + i * blockw + blockw / 2 ))
        byte="$(dd if="${tmp}" bs=1 skip="${xoff}" count=1 2>/dev/null | od -An -tu1 | tr -d ' ')"
        bit=$(( byte > 128 ? 1 : 0 ))
        val=$(( (val << 1) | bit ))
    done
    rm -f "${tmp}"
    echo "${val}"
}

# -----------------------------------------------------------------------
# run_marker_bframes_selfcheck — verifies marker_bframes.mp4 right after
# generation: (1) the container reports has_b_frames >= 1 (confirms real
# frame reordering made it into the encode, not just the request for it),
# and (2) a spread of sample frames (start, near-start, three spread across
# the middle, end) decode back to their expected index through the full
# H.264 encode/decode round trip. A marker clip whose own marker can't be
# trusted defeats the point of the fixture, so this is a hard failure, not
# a warning.
# -----------------------------------------------------------------------
run_marker_bframes_selfcheck() {
    local clip="${OUTPUT_DIR}/marker_bframes.mp4"
    local frames=$(( MARKER_FPS * MARKER_DURATION ))
    local has_b
    has_b="$(ffprobe -v error -select_streams v:0 -show_entries stream=has_b_frames -of default=nw=1:nk=1 "${clip}")"
    if [[ "${has_b}" -lt 1 ]]; then
        echo "ERROR: marker_bframes.mp4 self-check failed: has_b_frames=${has_b} (expected >= 1)" >&2
        exit 1
    fi
    echo "  self-check: has_b_frames=${has_b}"

    local sample_frames=(0 1 2 "$(( frames / 4 ))" "$(( frames / 2 ))" "$(( frames * 3 / 4 ))" "$(( frames - 2 ))" "$(( frames - 1 ))")
    local n got fail=0
    for n in "${sample_frames[@]}"; do
        got="$(decode_marker_value "${clip}" "${n}" "${WIDTH}" "${HEIGHT}" "${MARKER_BITS}")"
        if [[ "${got}" -ne "${n}" ]]; then
            echo "ERROR: marker_bframes.mp4 self-check failed: frame ${n} decoded as ${got}" >&2
            fail=1
        fi
    done
    if [[ "${fail}" -ne 0 ]]; then
        exit 1
    fi
    echo "  self-check: sample frames [${sample_frames[*]}] all decoded to their own index"
}

# -----------------------------------------------------------------------
# heaac.mp4 — see the header comment: libfdk_aac is unavailable and the
# native aac_he path can't round-trip through this ffmpeg build's own
# decoder, so it's skipped rather than faked.
# -----------------------------------------------------------------------
warn_heaac_skipped() {
    if ffmpeg -hide_banner -encoders 2>/dev/null | grep -q libfdk_aac; then
        echo "NOTE: libfdk_aac IS available in this ffmpeg build but gen_stress_media.sh" >&2
        echo "      does not yet use it — heaac.mp4 still needs implementing." >&2
    else
        echo "WARN: skipping heaac.mp4 — no libfdk_aac encoder in this ffmpeg build, and" >&2
        echo "      the native 'aac' encoder's -profile:a aac_he output can't be read back" >&2
        echo "      by this ffmpeg's own 'aac' decoder (\"Audio object type SBR+21 is not" >&2
        echo "      implemented\"), so it can't be ffprobe-verified either. Known limitation." >&2
    fi
}

gen_bframes
gen_surround51
gen_timecode
gen_combined
gen_marker_bframes
run_marker_bframes_selfcheck
warn_heaac_skipped

echo "Done: stress clips written to ${OUTPUT_DIR}"
