extends Control

# Smoke-test driver for the native media streams GDExtension.
#
# Loads the synthetic clip (generated by tools/gen_test_media.sh) into a stock
# VideoStreamPlayer and plays it. The VideoStreamPlayer pulls a
# PlatformVideoStreamPlayback, which decodes NV12 via AVFoundation and presents
# zero-copy through the NV12->RGB compute pipeline. If the frames appear and
# advance, the present path is visually correct (this is the HITL check).

@onready var player: VideoStreamPlayer = $VideoStreamPlayer
@onready var status: Label = $Status

# Point this at any .mp4/.mov/.m4v the OS can decode. The default is the
# synthetic fixture; copy it into the demo project's res:// to use res://.
@export var clip_path: String = "res://synthetic.mp4"


func _ready() -> void:
	var stream := ResourceLoader.load(clip_path)
	if stream == null:
		_set_status("FAILED to load: %s\n(generate it with tools/gen_test_media.sh and copy synthetic.mp4 into demo/)" % clip_path)
		return
	player.stream = stream
	player.play()
	_set_status("Playing %s" % clip_path)


func _process(_delta: float) -> void:
	if player.stream != null and player.is_playing():
		_set_status("Playing  pos=%.2fs  tex=%s" % [
			player.stream_position,
			"ok" if player.get_video_texture() != null else "null",
		])


func _set_status(msg: String) -> void:
	if status != null:
		status.text = msg
	print(msg)
